-- Generated by tools/update_suite_changelog.py from CHANGELOG.md. Do not edit directly.
local _, Suite = ...
Suite.Changelog = {
    sourceSha256 = "330651E28CA62DD45D0B0687E1245DDF23304BE66A13DD01792E971BC5D0FC7F",
    currentVersion = "1.0 Alpha 1",
    entries = {
        {
            version = "1.0 Alpha 1",
            date = "2026-09-25",
            sections = {
                { title = "Changes", bullets = {
                    "First public alpha package of the Suite core, optional modules, and Suite-owned Skinning module.",
                    "Retail Modern's factory Micro Bar uses the compact two-column layout beside the Damage Meter. WoW Forever keeps its own factory design.",
                    "Includes Suite pages inside MSUF Options, profile integration, and client-specific addon manifests.",
                    "Requires Midnight Simple Unit Frames. Retail and WoW Forever have offline contract coverage; live gameplay and visual testing are still needed.",
                    "Bags: profiles from before the Suite inventory views keep Blizzard's own item grid (new view choice Blizzard grid). The Suite views list slots in bag order, show every slot in combat and keep their tooltip lines.",
                } },
            },
        },
    },
}
