-- Generated by tools/update_suite_changelog.py from CHANGELOG.md. Do not edit directly.
local _, Suite = ...
Suite.Changelog = {
    sourceSha256 = "D30BE20D8F01047CBB34A01A9CA8AF5328627281A4D2115F6D61674700F05087",
    currentVersion = "1.0 Alpha 1",
    entries = {
        {
            version = "1.0 Alpha 1",
            date = "2026-09-25",
            sections = {
                { title = "Changes", bullets = {
                    "First public alpha package of the Suite core, optional modules, and Suite-owned Skinning module.",
                    "Retail Modern's factory Micro Bar uses the compact two-column layout beside the Damage Meter. WoW Forever keeps its own factory design.",
                    "Includes Suite pages inside MSUF Options, profile integration, and client-specific addon manifests.",
                    "Requires Midnight Simple Unit Frames. Retail and WoW Forever have offline contract coverage; live gameplay and visual testing are still needed.",
                } },
            },
        },
    },
}
