dofile(arg[1] .. "/tools/tests/suite_bh3_state_support.lua").Run("suite_skin_profile_import_contract.lua", [=[
BH3("S06-A2",function()
    assert(Database.SetActiveProfile("Default"));O.ClearHistory()
    assert(O.BeginUserChange("BH3 edit"));NS.DB.theme.colors.accent[1]=0.123;assert(O.CommitUserChange())
    assert(Database.SetActiveProfile("Other"));assert(Database.SetActiveProfile("Default"))
    assert(not O.Undo() and NS.DB.theme.colors.accent[1]==0.123,"S06-A2: A-B-A revived stale standalone history")
    local epoch=Database.GetHistoryEpoch()
    assert(Database.DeleteProfile("Other"));assert(Database.GetHistoryEpoch()>epoch,"S06-A2: deletion did not invalidate external snapshots")
end)
BH3("S06-A5",function()
    Database.SetActiveProfile("Default");O.RefreshAll()
    Database.SetProfile("CaptionTarget",Profile(0.3));Database.SetActiveProfile("CaptionTarget");O.RefreshAll()
    assert(lastStatus.text:find("CaptionTarget",1,true),"S06-A5: active profile caption stayed on the previous profile")
end)
]=])
