"""Build the Suite-owned in-game release history from CHANGELOG.md.

Run without arguments after editing the changelog, or use --check in gates.
"""

import argparse
import hashlib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "CHANGELOG.md"
OUTPUT = ROOT / "MSUF_Suite" / "Core" / "Changelog.lua"
TOC = ROOT / "MSUF_Suite" / "MSUF_Suite_Mainline.toc"


def lua_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def parse(source):
    entries = []
    for line in source.splitlines():
        release = re.fullmatch(r"##\s+(.+?)\s+-\s+(\d{4}-\d{2}-\d{2})\s*", line)
        if release:
            entries.append({"version": release.group(1), "date": release.group(2), "sections": []})
            continue
        if line.startswith("## "):
            raise ValueError(f"Invalid release heading: {line}")
        if not entries:
            continue
        section = re.fullmatch(r"###\s+(.+?)\s*", line)
        if section:
            entries[-1]["sections"].append({"title": section.group(1), "bullets": []})
            continue
        if line.startswith("- "):
            sections = entries[-1]["sections"]
            if not sections:
                sections.append({"title": "Changes", "bullets": []})
            sections[-1]["bullets"].append(line[2:].strip())
    if not entries or any(not section["bullets"] for entry in entries for section in entry["sections"]):
        raise ValueError("Suite changelog needs releases with nonempty sections")
    if any(not entry["sections"] for entry in entries):
        raise ValueError("Every Suite release needs at least one bullet")
    versions = [entry["version"] for entry in entries]
    if len(versions) != len(set(versions)):
        raise ValueError("Duplicate Suite release version")
    return entries


def render(source):
    entries = parse(source)
    toc = TOC.read_text(encoding="utf-8-sig")
    version = re.search(r"^## Version:\s*(\S+)\s*$", toc, re.MULTILINE)
    if not version or re.sub(r"[^a-z0-9]", "", version.group(1).lower()) != re.sub(
        r"[^a-z0-9]", "", entries[0]["version"].lower()
    ):
        raise ValueError("The latest Suite changelog heading must match the core TOC version")
    digest = hashlib.sha256(source.encode("utf-8")).hexdigest().upper()
    lines = [
        "-- Generated by tools/update_suite_changelog.py from CHANGELOG.md. Do not edit directly.",
        "local _, Suite = ...",
        "Suite.Changelog = {",
        f"    sourceSha256 = {lua_string(digest)},",
        f"    currentVersion = {lua_string(entries[0]['version'])},",
        "    entries = {",
    ]
    for entry in entries:
        lines.extend([
            "        {",
            f"            version = {lua_string(entry['version'])},",
            f"            date = {lua_string(entry['date'])},",
            "            sections = {",
        ])
        for section in entry["sections"]:
            lines.append(f"                {{ title = {lua_string(section['title'])}, bullets = {{")
            lines.extend(f"                    {lua_string(bullet)}," for bullet in section["bullets"])
            lines.append("                } },")
        lines.extend(["            },", "        },"])
    lines.extend(["    },", "}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the bundled Lua is stale")
    args = parser.parse_args()
    source = SOURCE.read_text(encoding="utf-8-sig").replace("\r\n", "\n").replace("\r", "\n")
    expected = render(source)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8").replace("\r\n", "\n") != expected:
            parser.error("MSUF_Suite/Core/Changelog.lua is stale; run tools/update_suite_changelog.py")
        print("Suite changelog is current")
    else:
        OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Updated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
